channels:
  - conda-forge
  - defaults
dependencies:
  - alembic
  - boost-cpp
  - flask
  - flask-httpauth
  - flask-migrate
  - flask-sqlalchemy
  - python
  - requests
  - sqlalchemy
  - sqlite
  - numpy
  - swig
  - sphinx
  - sphinx_rtd_theme
  - vina
  - openbabel
  - pip:
    - chembl-webresource-client
    - flask-cors
