"""empty message

Revision ID: 59241e2b314a
Revises: 
Create Date: 2023-01-19 15:46:47.193818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59241e2b314a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('request_state', sa.Enum('CREATED', 'ACCEPTED', 'REJECTED', name='masterrequeststate'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_request_client_id'), ['client_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('master_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_request_client_id'))

    op.drop_table('master_request')
    # ### end Alembic commands ###
