"""empty message

Revision ID: 0618dbad51d6
Revises: a014446cd62f
Create Date: 2023-04-11 11:28:18.195378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0618dbad51d6'
down_revision = 'a014446cd62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('params', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docking', schema=None) as batch_op:
        batch_op.drop_column('params')

    # ### end Alembic commands ###
