"""empty message

Revision ID: 1114cdbde1a9
Revises: 4b8bff5acd17
Create Date: 2023-01-04 20:09:16.312455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1114cdbde1a9'
down_revision = '4b8bff5acd17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('master_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('master_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###
