"""empty message

Revision ID: 229530b531ec
Revises: b60620810b9d
Create Date: 2023-07-23 03:04:06.755350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229530b531ec'
down_revision = 'b60620810b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_notification', schema=None) as batch_op:
        batch_op.alter_column('docking_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_notification', schema=None) as batch_op:
        batch_op.alter_column('docking_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###
