"""empty message

Revision ID: 29534f133de0
Revises: e2d974039cdd
Create Date: 2023-10-12 11:18:30.048113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29534f133de0'
down_revision = 'e2d974039cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docking', schema=None) as batch_op:
        batch_op.drop_column('error')

    # ### end Alembic commands ###
