"""empty message

Revision ID: 3b6ea116984f
Revises: 6668903ccf67
Create Date: 2022-12-20 18:53:00.384703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6ea116984f'
down_revision = '6668903ccf67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('OFFLINE', 'ONLINE', 'IDLE', 'BUSY', name='clientstate'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.Enum('OFFLINE', 'ONLINE', 'IDLE', 'BUSY', name='clientstate'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)

    # ### end Alembic commands ###
