"""empty message

Revision ID: 3d34e7b1b679
Revises: 0618dbad51d6
Create Date: 2023-06-06 21:48:48.418353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d34e7b1b679'
down_revision = '0618dbad51d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docking_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_compute_docking_id'), ['docking_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compute_docking_id'))
        batch_op.drop_column('docking_id')

    # ### end Alembic commands ###
