"""empty message

Revision ID: 4ad1369f8198
Revises: 5d004bb50d11
Create Date: 2023-03-16 10:46:44.133920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
from app.models.docking import ListType

# revision identifiers, used by Alembic.
revision = '4ad1369f8198'
down_revision = '5d004bb50d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docking', schema=None) as batch_op:
        batch_op.alter_column('worker_ids',
               existing_type=sqlite.JSON(),
               type_=ListType(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docking', schema=None) as batch_op:
        batch_op.alter_column('worker_ids',
               existing_type=ListType(),
               type_=sqlite.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###
