"""empty message

Revision ID: 4b8bff5acd17
Revises: 775f266394d6
Create Date: 2023-01-04 20:05:22.533536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8bff5acd17'
down_revision = '775f266394d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('worker_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('worker_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    op.create_table('test',
    sa.Column('a', sa.VARCHAR(length=10), nullable=True),
    sa.Column('b', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('a', 'b')
    )
    # ### end Alembic commands ###
