"""empty message

Revision ID: 4ba837fb2aa3
Revises: 6dda58bda5c7
Create Date: 2023-01-04 20:16:51.532564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba837fb2aa3'
down_revision = '6dda58bda5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('master_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('state_update_time', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Enum('CREATED', 'ACCEPTED', 'REJECTED', name='requeststate'), nullable=True),
    sa.PrimaryKeyConstraint('master_id', 'worker_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
