"""empty message

Revision ID: 648898b72d55
Revises: b90953d11b7d
Create Date: 2023-01-04 20:15:12.048681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648898b72d55'
down_revision = 'b90953d11b7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('master_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=True),
    sa.Column('state_update_time', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Enum('CREATED', 'ACCEPTED', 'REJECTED', name='requeststate'), nullable=True),
    sa.PrimaryKeyConstraint('master_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
