"""empty message

Revision ID: 6c5141ec6802
Revises: 3b6ea116984f
Create Date: 2022-12-21 01:51:21.823000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5141ec6802'
down_revision = '3b6ea116984f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('request_to', sa.String(length=36), nullable=False),
    sa.Column('request_from', sa.String(length=36), nullable=False),
    sa.Column('state_update_time', sa.DateTime(), nullable=False),
    sa.Column('state', sa.Enum('CREATED', 'ACCEPTED', 'REJECTED', name='requeststate'), nullable=True),
    sa.PrimaryKeyConstraint('request_to', 'request_from')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
