"""empty message

Revision ID: 775f266394d6
Revises: 6c5141ec6802
Create Date: 2022-12-22 19:13:20.485654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775f266394d6'
down_revision = '6c5141ec6802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('master_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('worker_id', sa.String(length=36), nullable=False))
        batch_op.drop_column('request_from')
        batch_op.drop_column('request_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_to', sa.VARCHAR(length=36), nullable=False))
        batch_op.add_column(sa.Column('request_from', sa.VARCHAR(length=36), nullable=False))
        batch_op.drop_column('worker_id')
        batch_op.drop_column('master_id')

    # ### end Alembic commands ###
