"""empty message

Revision ID: 80942e49892b
Revises: 
Create Date: 2025-07-10 14:58:45.950555

"""
from alembic import op
import sqlalchemy as sa
from app.models.docking import ListType

# revision identifiers, used by Alembic.
revision = '80942e49892b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('last_connected', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Enum('OFFLINE', 'ONLINE', 'IDLE', 'BUSY', name='clientstate'), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('compute',
    sa.Column('compute_id', sa.String(length=36), nullable=False),
    sa.Column('docking_id', sa.String(length=36), nullable=True),
    sa.Column('result', sa.TEXT(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Enum('COMPUTED', 'NOT_COMPUTED', 'COMPUTING', 'ERROR', name='computestate'), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('ligand', sa.TEXT(), nullable=True),
    sa.Column('ligand_name', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('compute_id')
    )
    with op.batch_alter_table('compute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compute_docking_id'), ['docking_id'], unique=False)

    op.create_table('docking',
    sa.Column('docking_id', sa.String(length=36), nullable=False),
    sa.Column('master_id', sa.String(length=36), nullable=False),
    sa.Column('worker_ids', ListType(), nullable=True),
    sa.Column('target', sa.TEXT(), nullable=True),
    sa.Column('target_name', sa.String(length=1000), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Enum('STARTED', 'FINISHED', 'ERROR', name='dockingstate'), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('docking_id')
    )
    with op.batch_alter_table('docking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_docking_master_id'), ['master_id'], unique=False)

    op.create_table('ligands',
    sa.Column('ligand_id', sa.String(length=36), nullable=False),
    sa.Column('ligand', sa.TEXT(), nullable=True),
    sa.Column('state', sa.Enum('COMPUTED', 'NOT_COMPUTED', name='ligandstate'), nullable=True),
    sa.PrimaryKeyConstraint('ligand_id')
    )
    op.create_table('worker_notification',
    sa.Column('docking_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('docking_id', 'worker_id')
    )
    with op.batch_alter_table('worker_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_notification_worker_id'), ['worker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_notification_worker_id'))

    op.drop_table('worker_notification')
    op.drop_table('ligands')
    with op.batch_alter_table('docking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_docking_master_id'))

    op.drop_table('docking')
    with op.batch_alter_table('compute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compute_docking_id'))

    op.drop_table('compute')
    op.drop_table('client')
    # ### end Alembic commands ###
