"""empty message

Revision ID: 8ae0594c6642
Revises: 4ba837fb2aa3
Create Date: 2023-01-07 19:57:34.944982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae0594c6642'
down_revision = '4ba837fb2aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute',
    sa.Column('compute_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('master_id', sa.String(length=36), nullable=False),
    sa.Column('target', sa.BLOB(), nullable=True),
    sa.Column('ligands', sa.BLOB(), nullable=True),
    sa.Column('result', sa.BLOB(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Enum('CREATED', 'STARTED', 'FINISHED', 'ERROR', name='computestate'), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('compute_id')
    )
    op.create_table('master_notification',
    sa.Column('compute_id', sa.String(length=36), nullable=False),
    sa.Column('master_id', sa.String(length=36), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('compute_id')
    )
    with op.batch_alter_table('master_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_notification_master_id'), ['master_id'], unique=False)

    op.create_table('worker_notification',
    sa.Column('compute_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('compute_id')
    )
    with op.batch_alter_table('worker_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_notification_worker_id'), ['worker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_notification_worker_id'))

    op.drop_table('worker_notification')
    with op.batch_alter_table('master_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_notification_master_id'))

    op.drop_table('master_notification')
    op.drop_table('compute')
    # ### end Alembic commands ###
