"""empty message

Revision ID: 905af2fda2e4
Revises: 8ae0594c6642
Create Date: 2023-01-07 23:05:47.242989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905af2fda2e4'
down_revision = '8ae0594c6642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute', schema=None) as batch_op:
        batch_op.alter_column('target',
               existing_type=sa.BLOB(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ligands',
               existing_type=sa.BLOB(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('result',
               existing_type=sa.BLOB(),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute', schema=None) as batch_op:
        batch_op.alter_column('result',
               existing_type=sa.TEXT(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('ligands',
               existing_type=sa.TEXT(),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('target',
               existing_type=sa.TEXT(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
