"""empty message

Revision ID: a014446cd62f
Revises: 2cf5d7925cbc
Create Date: 2023-03-20 12:37:25.948301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a014446cd62f'
down_revision = '2cf5d7925cbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_compute')
    with op.batch_alter_table('compute', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ligand', sa.TEXT(), nullable=True))
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('COMPUTED', 'NOT_COMPUTED', 'COMPUTING', 'ERROR', name='computestate'),
               existing_nullable=True)
        batch_op.drop_column('worker_id')
        batch_op.drop_column('target_name')
        batch_op.drop_column('target')
        batch_op.drop_column('ligands')
        batch_op.drop_column('master_id')
        batch_op.drop_column('ligands_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compute', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ligands_name', sa.VARCHAR(length=1000), nullable=True))
        batch_op.add_column(sa.Column('master_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.add_column(sa.Column('ligands', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('target', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('target_name', sa.VARCHAR(length=1000), nullable=True))
        batch_op.add_column(sa.Column('worker_id', sa.VARCHAR(length=36), nullable=False))
        batch_op.alter_column('state',
               existing_type=sa.Enum('COMPUTED', 'NOT_COMPUTED', 'COMPUTING', 'ERROR', name='computestate'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.drop_column('ligand')

    op.create_table('_alembic_tmp_compute',
    sa.Column('compute_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('result', sa.TEXT(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('state', sa.VARCHAR(length=12), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('ligand', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('compute_id')
    )
    # ### end Alembic commands ###
