"""empty message

Revision ID: a8284b069af1
Revises: 723625ba0f81
Create Date: 2023-07-23 03:35:50.925760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8284b069af1'
down_revision = '723625ba0f81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_notification',
    sa.Column('docking_id', sa.String(length=36), nullable=False),
    sa.Column('worker_id', sa.String(length=36), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('docking_id', 'worker_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_notification')
    # ### end Alembic commands ###
