"""empty message

Revision ID: b60620810b9d
Revises: e2d974039cdd
Create Date: 2023-07-23 02:56:49.809271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60620810b9d'
down_revision = 'e2d974039cdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_notification', schema=None) as batch_op:
        batch_op.drop_index('ix_worker_notification_worker_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker_notification', schema=None) as batch_op:
        batch_op.create_index('ix_worker_notification_worker_id', ['worker_id'], unique=False)

    # ### end Alembic commands ###
