"""empty message

Revision ID: b90953d11b7d
Revises: 1114cdbde1a9
Create Date: 2023-01-04 20:12:14.371236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b90953d11b7d'
down_revision = '1114cdbde1a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('master_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.alter_column('master_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###
