"""users table

Revision ID: e691afe241db
Revises: fceef2479ab0
Create Date: 2022-12-17 21:29:58.348079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e691afe241db'
down_revision = 'fceef2479ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('last_connected', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Enum('connected', 'idle', 'busy', 'computing', name='status'), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client')
    # ### end Alembic commands ###
